site_name: Mishmash Kitchen
site_description: A feast for the hungriest in you

repo_url: https://github.com/artu-hnrq/mishmash_kitchen
site_url: https://artu-hnrq.github.io/mishmash_kitchen

docs_dir: pages
site_dir: _docs
use_directory_urls: false

theme: readthedocs

nav:
  - General:
    - Home: 'index.md'
    - Challenge: 'challenge.pdf'
  - Project:
    - Project setup: 'setup.md'
    - Development management: 'management.md'
    - Configuration: 'configuration.md'
    - Solution: 'solution.md'
  - Resources:
      Source code: 'https://github.com/artu-hnrq/Mishmash_Kitchen'
      License: 'https://choosealicense.com/licenses/gpl-3.0/'
      Postman workspace: 'https://app.getpostman.com/join-team?invite_code=bf91c969246261a2b3d423cb0390d112&ws=50e0f2a1-eb23-467c-bcd7-78f231f9d783'
